### ISSUE TITLE
Content Available is not set

### ISSUE THREAD

**Issue by byfoz** [CoreProc/fcm#11]
Hey!

I have been debugging why notifications sent using this package weren't being received when an iOS app was in the background.
On investigation it looks like `content_available` is never set in the payload sent to FCM despite it being a property on the `FcmMessage` class.

If you look at `NotificationChannels\Fcm\FcmMessage` you will see the toArray function used does not include this. 

```
    public function toArray()
    {
        return [
            'to'               => $this->to,
            'registration_ids' => $this->registrationIds,
            'condition'        => $this->condition,
            'collapse_key'     => $this->collapseKey,
            'priority'         => $this->priority,
            'time_to_live'     => $this->timeToLive,
            'dry_run'          => $this->dryRun,
            'data'             => $this->data,
            'notification'     => $this->notification->toArray(),
        ];
    }
```

I fixed this in my project by extending the `FcmMessage` class and overriding the `toArray()` method to include `'content_available' => true` when the instance property is true.

**Comment by chrisbjr** [comment]
Hi @CImrie thanks for noticing! We were getting this issue ourselves as well but we haven't done a full investigation yet. Glad you found the missing variables.

I've pushed a fix and tagged it as v1.1.1

Thanks!
