### ISSUE TITLE
Undefinded variable message

### ISSUE THREAD

**Issue by mgf145** [CoreProc/fcm#17]
hello.
i am getting error when sending message after updating to 1.3.0.
i am working on laravel 5.5 and the error is undefinded variable message in vendor/coreproc/laravel-notification-channel-fcm/src/FcmChannel.php on line 54.
please fix this.
 thank you.

**Comment by mgf145** [comment]
#9020e7c

**Comment by chrisbjr** [comment]
Hi @mgf145 yes, there was a bug but was fixed using recent pull requests.

Please update to 1.3.1
