### ISSUE TITLE
How to Send push notification To Topics ?

### ISSUE THREAD

**Issue by jo-zef** [CoreProc/fcm#5]
Please can you give an exemple how to send a push notification To Topics ?

**Comment by danieljaniga** [comment]
You can use `tag` property

**Comment by chrisbjr** [comment]
Hi @twsjozef did that solve your issue?

**Comment by jo-zef** [comment]
Hi @danieljaniga thanks for your reply i will try to test it
Hi @chrisbjr  , Realy i didint try it , i changed it with a simple curl request

**Comment by chrisbjr** [comment]
@twsjozef show me the curl request, I'm sure you can convert that into a notification

**Comment by chrisbjr** [comment]
Hi @twsjozef will close this now.
